name: cicd

on:
  push: 
    branches: [ "main" ]

  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository to GitHub Action runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # Initialize submodules if any
    - name: Initialize Submodules
      run: git submodule update --init --recursive

    - id: auth
      uses: google-github-actions/auth@v2.0.0
      with:
        workload_identity_provider: 'projects/82620805336/locations/global/workloadIdentityPools/my-pool-st/providers/githubprovider'
        service_account: 'secretssa@kd-project-437712.iam.gserviceaccount.com'

    # Terraform Init
    - name: Terraform Init
      run: |
        cd templatesProjectIAMBinding
        terraform init

  validate: 
     runs-on: ubuntu-latest
     needs: init

     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/82620805336/locations/global/workloadIdentityPools/my-pool-st/providers/githubprovider'
          service_account: 'secretssa@kd-project-437712.iam.gserviceaccount.com'
     
      # Terraform Validate
      - name: Terraform Validate
        run: |
         cd templatesProjectIAMBinding
         terraform init
         terraform validate

  tflint:
    needs: validate
    uses: ./.github/workflows/tflint.yaml
      
  plan: 
     runs-on: ubuntu-latest
     needs: tflint

     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/82620805336/locations/global/workloadIdentityPools/my-pool-st/providers/githubprovider'
          service_account: 'secretssa@kd-project-437712.iam.gserviceaccount.com'

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd templatesProjectIAMBinding
          terraform plan --var-file=folder.tfvars

  apply: 
     runs-on: ubuntu-latest
     needs: plan

     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/82620805336/locations/global/workloadIdentityPools/my-pool-st/providers/githubprovider'
          service_account: 'secretssa@kd-project-437712.iam.gserviceaccount.com'

      # Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd templatesProjectIAMBinding
          terraform apply -auto-approve -input=false
