name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      target_dir:
        description: 'Specify the subdirectory to destroy resources from (e.g.,compute , bucket, gke, database)'
        required: true
        default: ''

jobs:
  tf-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v0.4.0  
        with:
         workload_identity_provider: 'projects/82620805336/locations/global/workloadIdentityPools/my-pool-st/providers/githubprovider'
         service_account: 'secretssa@kd-project-437712.iam.gserviceaccount.com'

      - name: Debug target directory
        run: echo "Target directory: ${{ github.event.inputs.target_dir }}"

      - name: Terraform Init
        run: |
          cd ./templatesProjectIAMBinding/${{ github.event.inputs.target_dir }}
          terraform init

      - name: Terraform Destroy
        id: destroy
        run: |
          cd ./templatesProjectIAMBinding/${{ github.event.inputs.target_dir }}
          terraform destroy --auto-approve -input=false
